name: macos-terminal-theme
when: os == "macos"

provision:
  when: declaration == "macos.terminal.theme"

executable: macos-terminal-theme.sh

schema:
  $schema: https://json-schema.org/draft/2020-12/schema
  type: string
