name: git-repo
when: os in ["macos", "linux"]
after: packages

provision:
  when: declaration == "git.repo"

executable: git-repo.sh

# TODO: shouldn't be required on mac, and I don't have any package plugins for linux yet...
# dependencies:
#   packages:
#     - git
