name: git-repo
when: family == "unix"
after: packages

provision:
  when: declaration == "git.repo"

executable: git-repo.sh

# TODO: shouldn't be required on mac, and I don't have any package plugins for linux yet...
# dependencies:
#   packages:
#     - git

schema:
  $schema: https://json-schema.org/draft/2020-12/schema
  type: object
  properties:
    source:
      type: string
    destination:
      type: string
    update:
      type: boolean
  required:
    - source
    - destination
