name: hostname

provision:
  when: declaration == "hostname"


schema:
  $schema: https://json-schema.org/draft/2020-12/schema
  type: string

---
when: family == "unix"
executable: hostname.sh

---
when: os == "windows"
executable: hostname.ps1
