name: nix-cli
when: family == "unix"

provision:
  when:
    - declaration == "packages"
    - state == "nix"

executable: nix-cli.sh

schema:
  $schema: https://json-schema.org/draft/2020-12/schema
  type: string
