name: files

provision:
  when: declaration == "files"

schema:
  $schema: https://json-schema.org/draft/2020-12/schema
  type: object
  properties:
    source:
      type: string
    destination:
      type: string
    link_files:
      type: boolean
  required:
    - source
    - destination

---
when:
 - os == "macos"
 - arch == "x86_64"
executable: assets/x86_64-apple-darwin/files

---
when:
  - os == "macos"
  - arch == "aarch64"
executable: assets/aarch64-apple-darwin/files

---
when:
  - os == "linux"
  - arch == "x86_64"
executable: assets/x86_64-unknown-linux-musl/files

---
when:
  - family == "windows"
  - arch == "x86_64"
executable: assets/x86_64-pc-windows-msvc/files.exe
