name: files
when: os in ["macos", "linux"]

provision:
  when: declaration == "files"

executable: files.sh

schema:
  $schema: https://json-schema.org/draft/2020-12/schema
  type: object
  properties:
    source:
      type: string
    destination:
      type: string
    link_files:
      type: boolean
  required:
    - source
    - destination
