name: chocolatey
when: os == "windows"

provision:
  when: declaration in ["packages", "packages.chocolatey"]

executable: chocolatey.ps1

schema:
  $schema: https://json-schema.org/draft/2020-12/schema
  type: string
