name: release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Determine New Version
        id: version
        uses: zwaldowski/semver-release-action@v2
        with:
          dry_run: true
          bump: minor
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set Env
        env:
          TAG: v${{ steps.version.outputs.version }}
        run: echo "TAG=${TAG}" >> $GITHUB_ENV
      - name: Install nk
        run: |
          # install nk
          curl -fsSL 'https://raw.githubusercontent.com/ciiqr/nk/HEAD/install.sh' | bash

          # add to path
          echo "${HOME}/.nk/bin" >> $GITHUB_PATH
      - name: Build assets
        env:
          REPOSITORY_NAME: ${{ github.event.repository.name }}
        run: |
          nk plugin pack \
            --owner "$GITHUB_REPOSITORY_OWNER" \
            --repo "$REPOSITORY_NAME" \
            --version "$TAG" \
            ./*/plugin.yml
      - name: Create Release
        env:
          GITHUB_USER: ${{ github.repository_owner }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create \
            --title "$TAG" \
            --notes '' \
            "$TAG" \
            manifest.yml *.tar.gz
