name: release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Determine New Version
        id: version
        uses: zwaldowski/semver-release-action@v2
        with:
          dry_run: true
          bump: minor
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set Env
        env:
          TAG: v${{ steps.version.outputs.version }}
        run: echo "TAG=${TAG}" >> $GITHUB_ENV
      - name: Build assets
        run: ./scripts/build-assets.sh
      - name: Create Release
        env:
          GITHUB_USER: ${{ github.repository_owner }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create \
            --title "$TAG" \
            --notes '' \
            "$TAG" \
            *.tar.gz
